# Generated by Django 5.0.6 on 2024-05-25 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VMPurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vm_name', models.CharField(max_length=100)),
                ('vm_cores', models.IntegerField()),
                ('vm_memory', models.IntegerField()),
                ('disk_size', models.IntegerField()),
                ('is_confirmed', models.BooleanField(default=False)),
            ],
        ),
    ]
