# Generated by Django 5.0.6 on 2024-05-26 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myform', '0002_purchase_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='status',
        ),
    ]
