# Generated by Django 5.0.6 on 2024-05-26 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myform', '0003_remove_purchase_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='vm_name',
            field=models.CharField(max_length=100),
        ),
    ]
