# Generated by Django 5.0.6 on 2024-05-28 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myform', '0004_alter_purchase_vm_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
